version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  labels: []
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7

# Rust:
- package-ecosystem: "cargo"
  directory: "/"
  labels: []
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 7
- package-ecosystem: "cargo"
  directory: "/compiler-cli"
  labels: []
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 7
- package-ecosystem: "cargo"
  directory: "/compiler-core"
  labels: []
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 7
- package-ecosystem: "cargo"
  directory: "/compiler-wasm"
  labels: []
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 7
- package-ecosystem: "cargo"
  # Does not have any custom deps right now,
  # but can add them in the future:
  directory: "/test-package-compiler"
  labels: []
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 7
