// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Gleam contributors

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Policy {
    /// Name of repository
    #[prost(string, required, tag = "1")]
    pub repository: ::prost::alloc::string::String,
    /// Policy name within the repository
    /// (matches ^[a-z0-9][a-z0-9_\-\.]*\[a-z0-9\]$, length 3..64)
    #[prost(string, required, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Optional, free-form description (admin-set, surfaced in CLI/UI)
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether the policy is publicly readable or restricted to org members.
    /// Read at the edge to decide whether to enforce auth on the fetch.
    /// Adding new Visibility values is a breaking change — old clients will
    /// treat unknown values as PRIVATE per the fail-closed rule.
    #[prost(enumeration = "Visibility", required, tag = "4")]
    pub visibility: i32,
    /// One entry per repository the policy constrains (in practice "hexpm" and
    /// the org's own repository). A candidate release is matched to the entry
    /// whose repository equals the release's repository; a release from a
    /// repository with no matching entry is unconstrained by this policy.
    #[prost(message, repeated, tag = "5")]
    pub repositories: ::prost::alloc::vec::Vec<RepositoryPolicy>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryPolicy {
    /// Repository this entry applies to (e.g. "hexpm" or the org's repository).
    #[prost(string, required, tag = "1")]
    pub repository: ::prost::alloc::string::String,
    /// Baseline limits applied to every release in this repository. Unset = no
    /// restriction. Restrictions never apply to releases permitted by an ALLOW
    /// override (those bypass all limits).
    #[prost(message, optional, tag = "2")]
    pub restriction: ::core::option::Option<Restriction>,
    /// Per-package final say, evaluated against each release in this repository.
    /// An ALLOW override permits the release immediately and bypasses
    /// `restriction`; a DENY override blocks it. When multiple overrides match a
    /// release, the one with the most specific requirement wins.
    #[prost(message, repeated, tag = "3")]
    pub overrides: ::prost::alloc::vec::Vec<Override>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Restriction {
    /// Advisory limit. If set, deny any release whose maximum advisory severity
    /// is at least this value. Unset = no advisory limit.
    #[prost(enumeration = "super::package::AdvisorySeverity", optional, tag = "1")]
    pub advisory_min_severity: ::core::option::Option<i32>,
    /// Retirement limit. If non-empty, deny any release retired with a reason in
    /// this set. Empty = no retirement limit.
    #[prost(enumeration = "super::package::RetirementReason", repeated, tag = "2")]
    pub retirement_reasons: ::prost::alloc::vec::Vec<i32>,
    /// Minimum release age. Same duration grammar as the Hex cooldown config
    /// ("7d", "2w", "1mo", "0"). Unset or "0" = no minimum age. If multiple
    /// active policies declare cooldowns, the effective cooldown is the strictest.
    #[prost(string, optional, tag = "3")]
    pub cooldown: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PackageRef {
    /// Package name.
    #[prost(string, required, tag = "1")]
    pub package: ::prost::alloc::string::String,
    /// Optional version requirement (e.g. "~> 1.7"). Unset = the whole package.
    #[prost(string, optional, tag = "2")]
    pub requirement: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Override {
    /// Whether this override permits or blocks the matching release.
    #[prost(enumeration = "OverrideAction", required, tag = "1")]
    pub action: i32,
    /// The package (and optional requirement) the override applies to.
    #[prost(message, required, tag = "2")]
    pub r#ref: PackageRef,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Visibility {
    /// PRIVATE is the safe default; unknown enum values must be treated as PRIVATE.
    Private = 0,
    Public = 1,
}
impl Visibility {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Private => "VISIBILITY_PRIVATE",
            Self::Public => "VISIBILITY_PUBLIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VISIBILITY_PRIVATE" => Some(Self::Private),
            "VISIBILITY_PUBLIC" => Some(Self::Public),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OverrideAction {
    /// Permit the release and bypass `restriction`.
    Allow = 0,
    /// Block the release.
    Deny = 1,
}
impl OverrideAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Allow => "OVERRIDE_ACTION_ALLOW",
            Self::Deny => "OVERRIDE_ACTION_DENY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OVERRIDE_ACTION_ALLOW" => Some(Self::Allow),
            "OVERRIDE_ACTION_DENY" => Some(Self::Deny),
            _ => None,
        }
    }
}
