# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# The `FIX-DEADLINE` lines are used by the test suite, and once the date
# they specify has passed they will cause a deadline check test to fail. This
# is to ensure that we do not forget to fix these.
#
[[advisories.ignore]]
id = "RUSTSEC-2026-0173"
reason = """
proc-macro-error2 is currently unmaintained.
https://rustsec.org/advisories/RUSTSEC-2024-0370

At time of writing, it is used by a single transitive dependency.

   $ cargo tree -i proc-macro-error2
   proc-macro-error2 v2.0.1
   └── i18n-embed-fl v0.9.2
       └── age v0.11.3
           └── gleam-core

https://github.com/gleam-lang/gleam/issues/5829

FIX-DEADLINE: 2026-10-08
"""

[[advisories.ignore]]
id = "RUSTSEC-2025-0141"
reason = """
Bincode is currently unmaintained.
https://rustsec.org/advisories/RUSTSEC-2025-0141.html

We need to migrate to some other package.
https://github.com/gleam-lang/gleam/issues/5827

FIX-DEADLINE: 2026-10-08
"""

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = false
registries = []

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    # "https://github.com/gleam-lang/hexpm-rust",
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]
