// TODO: contains
// TODO: delete
// TODO: difference
// TODO: from_list
// TODO: intersection
// TODO: is_disjoint
// TODO: is_subset
// TODO: new
// TODO: put
// TODO: size
// TODO: to_list
// TODO: union
