version: 2
jobs:
  build_compiler:
    working_directory: ~/tmp
    docker:
      - image: rust:1.33
    steps:
      - checkout

      - restore_cache:
          key: gleam-compiler-cargo-{{ checksum "gleam/Cargo.toml" }}

      - run: cd gleam && cargo test
      - run: cd gleam && cargo build --release
      - run: gleam/target/release/gleam --version

      - save_cache:
          key: gleam-compiler-cargo-{{ checksum "gleam/Cargo.toml" }}
          paths:
            - /usr/local/cargo/registry
            - gleam/target
            - ~/.cargo/


# https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  ci:
    jobs:
      - build_compiler
