name: Feature Request
description: Create a feature request
labels: ["request"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description of the feature or enhancement."
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area does this relate to
      options:
        - area:ci
        - area:codegen
        - area:documentation
        - area:errors
        - area:formatter
        - area:language-design
        - area:parser
        - area:tooling
        - area:type-analysis
        - area:web-dev 
    validations:
      required: false
  - type: input
    attributes:
      label: Gleam Version
      description: "The Gleam version used"
      placeholder: "0.20.1"
    validations:
      required: false
