name: Other
description: Create a feature request, enhancement, proposal or suggestion
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description of the request, feature, proposal or enhancement."
      placeholder: |
        Please use the Gleam's Community Discord https://discord.com/invite/Fm8Pwmy or Gleam's GitHub Discussions https://github.com/gleam-lang/gleam/discussions for questions!
    validations:
      required: true
