name: Other
description: Create a feature request, enhancement proposal or suggestion
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description of the request, feature, proposal or enhancement."
    validations:
      required: true
