//! This file is generated by build.rs
//! Do not edit it directly, instead add new test cases to ./cases

#[test]
fn erlang_import() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_import");
    insta::assert_snapshot!(
        "erlang_import",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_import"
    );
}

#[test]
fn erlang_nested() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_nested");
    insta::assert_snapshot!(
        "erlang_nested",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_nested"
    );
}

#[test]
fn javascript_d_ts() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/javascript_d_ts");
    insta::assert_snapshot!(
        "javascript_d_ts",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/javascript_d_ts"
    );
}

#[test]
fn erlang_empty() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_empty");
    insta::assert_snapshot!(
        "erlang_empty",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_empty"
    );
}

#[test]
fn hello_joe() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/hello_joe");
    insta::assert_snapshot!(
        "hello_joe",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/hello_joe"
    );
}

#[test]
fn erlang_import_shadowing_prelude() {
    let output = crate::prepare(
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_import_shadowing_prelude",
    );
    insta::assert_snapshot!(
        "erlang_import_shadowing_prelude",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/erlang_import_shadowing_prelude"
    );
}

#[test]
fn javascript_empty() {
    let output =
        crate::prepare("/Users/louis/src/gleam/gleam/test-package-compiler/cases/javascript_empty");
    insta::assert_snapshot!(
        "javascript_empty",
        output,
        "/Users/louis/src/gleam/gleam/test-package-compiler/cases/javascript_empty"
    );
}
