name = "test_community_packages"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.36.0 and < 1.0.0"
argamak = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
aws4_request = ">= 0.1.1 and < 1.0.0"
bigi = ">= 2.1.0 and < 3.0.0"
birdie = ">= 1.1.0 and < 2.0.0"
cgi = ">= 1.0.1 and < 2.0.0"
conversation = ">= 1.4.3 and < 2.0.0"
edit_distance = ">= 2.0.1 and < 3.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"
exercism_test_runner = ">= 1.7.0 and < 2.0.0"
filepath = ">= 0.2.0 and < 1.0.0"
gap = ">= 1.1.3 and < 2.0.0"
gen_core_erlang = ">= 0.5.1 and < 1.0.0"
gen_gleam = ">= 0.3.1 and < 1.0.0"
glance = ">= 0.8.2 and < 1.0.0"
glance_printer = ">= 1.1.0 and < 2.0.0"
glatus = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.0 and < 2.0.0"
gleam_community_colour = ">= 1.4.0 and < 2.0.0"
gleam_community_maths = ">= 1.1.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_elli = ">= 2.4.0 and < 3.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_fetch = ">= 0.4.0 and < 1.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_json = ">= 0.7.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_pgo = ">= 0.6.1 and < 1.0.0"
gleam_sendgrid = ">= 0.2.0 and < 1.0.0"
gleamy_bench = ">= 0.4.0 and < 1.0.0"
glearray = ">= 0.2.1 and < 1.0.0"
gleescript = ">= 1.0.0 and < 2.0.0"
glen = ">= 2.0.0 and < 3.0.0"
glenvy = ">= 0.5.1 and < 1.0.0"
glesha = ">= 0.1.3 and < 1.0.0"
glexer = ">= 0.7.0 and < 1.0.0"
glisten = ">= 2.0.0 and < 3.0.0"
globe = ">= 0.1.0 and < 1.0.0"
gsv = ">= 1.4.0 and < 2.0.0"
htmb = ">= 2.0.0 and < 3.0.0"
htmgrrrl = ">= 0.3.0 and < 1.0.0"
ids = ">= 0.12.0 and < 1.0.0"
iso_8859 = ">= 2.0.0 and < 3.0.0"
jot = ">= 0.3.1 and < 1.0.0"
justin = ">= 1.0.1 and < 2.0.0"
lustre = ">= 3.1.4 and < 4.0.0"
lustre_http = ">= 0.5.0 and < 1.0.0"
lustre_ui = ">= 0.4.0 and < 1.0.0"
lustre_websocket = ">= 0.7.6 and < 1.0.0"
marceau = ">= 1.1.0 and < 2.0.0"
mineflayer = ">= 0.1.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"
mug = ">= 0.2.0 and < 1.0.0"
nakai = ">= 0.9.0 and < 1.0.0"
nibble = ">= 1.1.0 and < 2.0.0"
outil = ">= 0.5.0 and < 1.0.0"
phony = ">= 1.1.6 and < 2.0.0"
plinth = ">= 0.1.13 and < 1.0.0"
prng = ">= 3.0.2 and < 4.0.0"
process_waiter = ">= 1.0.0 and < 2.0.0"
puddle = ">= 0.5.0 and < 1.0.0"
punycode = ">= 0.1.1 and < 1.0.0"
radish = ">= 0.13.0 and < 1.0.0"
ranger = ">= 1.2.0 and < 2.0.0"
rank = ">= 1.0.0 and < 2.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"
simplifile = ">= 1.5.1 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"
spinner = ">= 1.1.0 and < 2.0.0"
testbldr = ">= 1.1.0 and < 2.0.0"
tom = ">= 0.3.0 and < 1.0.0"
wimp = ">= 1.1.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
zeptomail = ">= 1.0.0 and < 2.0.0"
jwt = ">= 0.1.11 and < 1.0.0"
jasper = ">= 1.2.0 and < 2.0.0"
immutable_lru = ">= 1.0.1 and < 2.0.0"
xmleam = ">= 1.1.4 and < 2.0.0"
pears = ">= 0.3.0 and < 1.0.0"
typed_headers = ">= 1.1.2 and < 2.0.0"
reactive_signal = ">= 0.0.1 and < 1.0.0"
nanoworker = ">= 0.0.2 and < 1.0.0"
file_streams = ">= 0.3.1 and < 1.0.0"
morse_code_translator = ">= 2.0.0 and < 3.0.0"
gleeunit = ">= 1.1.2 and < 2.0.0"
