name = "test_community_packages"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.34"
argamak = "~> 1.0"
argv = "~> 1.0"
aws4_request = "~> 0.1"
bigi = "~> 1.0"
birdie = "~> 1.0"
cgi = "~> 1.0"
conversation = "~> 1.4"
edit_distance = "~> 2.0"
envoy = "~> 1.0"
exception = "~> 1.1"
exercism_test_runner = "~> 1.7"
filepath = "~> 0.1"
gap = "~> 1.1"
gen_core_erlang = "~> 0.5"
gen_gleam = "~> 0.3"
glance = "~> 0.8"
glance_printer = "~> 1.1"
glatus = "~> 1.0"
gleam_community_ansi = "~> 1.4"
gleam_community_colour = "~> 1.3"
gleam_community_maths = "~> 1.0"
gleam_crypto = "~> 1.0"
gleam_elli = "~> 2.3"
gleam_erlang = "~> 0.24"
gleam_fetch = "~> 0.3"
gleam_hackney = "~> 1.2"
gleam_http = "~> 3.5"
gleam_httpc = "~> 2.1"
gleam_javascript = "~> 0.7"
gleam_json = "~> 0.7"
gleam_otp = "~> 0.9"
gleam_pgo = "~> 0.6"
gleam_sendgrid = "~> 0.2"
gleamy_bench = "~> 0.3"
glearray = "~> 0.2"
gleescript = "~> 1.0"
glen = "~> 2.0"
glenvy = "~> 0.5"
glesha = "~> 0.1"
glevatar = "~> 0.1"
glexer = "~> 0.7"
glisten = "~> 0.10"
globe = "~> 0.1"
gsv = "~> 1.3"
htmb = "~> 2.0"
htmgrrrl = "~> 0.3"
hug = "~> 1.0"
ids = "~> 0.12"
iso_8859 = "~> 1.0"
jot = "~> 0.2"
justin = "~> 1.0"
lustre = "~> 3.1"
lustre_http = "~> 0.5"
lustre_ui = "~> 0.3"
lustre_websocket = "~> 0.7"
marceau = "~> 1.1"
mineflayer = "~> 0.1"
mist = "~> 0.17"
mug = "~> 0.2"
nakai = "~> 0.9"
nibble = "~> 1.0"
outil = "~> 0.5"
phony = "~> 1.1"
plinth = "~> 0.1"
prng = "~> 3.0"
process_waiter = "~> 1.0"
puddle = "~> 0.5"
punycode = "~> 0.1"
radish = "~> 0.13"
ranger = "~> 1.1"
rank = "~> 1.0"
repeatedly = "~> 2.1"
simplifile = "~> 1.4"
snag = "~> 0.3"
spinner = "~> 1.0"
testbldr = "~> 1.1"
tom = "~> 0.3"
wimp = "~> 1.1"
wisp = "~> 0.1"
zeptomail = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
