# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2021 The Gleam contributors

name = "example"
version = "1.0.0"
target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
