name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}
  schedule:
    - cron: "45 0 * * *"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  VERSION: "${{ github.event_name == 'push' && github.ref_name || 'nightly' }}"

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  prepare-nightly:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should-run: ${{ steps.should-run.outputs.should-run }}
    if: ${{ github.repository == 'gleam-lang/gleam' && github.event_name != 'push' }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should-run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --after="24 hours" ${{ github.sha }}) && echo "should-run=false" >> $GITHUB_OUTPUT

      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        if: ${{ steps.should-run != 'false' }}
        with:
          token: ${{ github.token }}
          tag: nightly
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: |
            *.zip
            *.tar.gz
            *.sha256
            *.sha512

  build-release:
    name: build-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        toolchain: [ stable ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary: x86-64
            cargo-tool: cross
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            binary: aarch64
            cargo-tool: cross
          # macos>=14 runs exclusively on aarch64 and will thus fail to execute properly for x64
          - os: macos-13
            target: x86_64-apple-darwin
            binary: x86_64
            cargo-tool: cargo
          - os: macos-latest
            target: aarch64-apple-darwin
            binary: arm64
            cargo-tool: cargo
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: x86-64
            cargo-tool: cargo
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
            cargo-tool: wasm-pack
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update versions
        if: ${{ env.VERSION == 'nightly' }}
        shell: bash
        run: ./bin/add-nightly-suffix-to-versions.sh

      - name: "Build Archive"
        id: build
        uses: "./.github/actions/build-release"
        with:
          version: ${{ env.VERSION }}
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          cargo-tool: ${{ matrix.cargo-tool }}
          binary: ${{ matrix.binary }}

      - name: Upload release archive
        # https://github.com/softprops/action-gh-release/issues/445
        # uses: softprops/action-gh-release@v2
        uses: softprops/action-gh-release@0bd7e8b279c9b5b36661d552472fbbfe671fe26e
        with:
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: "${{ steps.build.outputs.files }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.target }}
          path: "${{ steps.build.outputs.files }}"
          overwrite: true

  build-container-images:
    name: build-container-images
    needs: [ build-release ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.repository == 'gleam-lang/gleam' && needs.prepare-nightly.outputs.should-run != 'false') }}
    strategy:
      matrix:
        base-image:
          - scratch
          - erlang
          - erlang-slim
          - erlang-alpine
          - elixir
          - elixir-slim
          - elixir-alpine
          - node
          - node-slim
          - node-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: containers

      - name: Download Gleam release from previous job
        uses: actions/download-artifact@v4
        with:
          pattern: release-{x86_64-unknown-linux-musl,aarch64-unknown-linux-musl}

      - name: "Unpack and rearrange release"
        shell: bash
        run: |
          declare -A ARCH
          ARCH["amd64"]="x86_64-unknown-linux-musl"
          ARCH["arm64"]="aarch64-unknown-linux-musl"

          for SHORT in "${!ARCH[@]}"; do
            LONG="${ARCH[$SHORT]}"

            # Unpack Release
            tar xf \
              "release-$LONG/gleam-$VERSION-$LONG.tar.gz" \
              -C "release-$LONG"

            # Move files into place
            mv "release-$LONG/gleam" "gleam-$SHORT"

            # Delete Unused Files
            rm -rf "release-$LONG"
          done

      - name: Authenticate with GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build version and tags
        id: versions
        run: |
          # Strip `v` prefix from version
          BARE_VERSION=$(echo "$VERSION" | sed -e 's|^v/\(.*\)|\1|')

          # Build version with platform
          PLATFORM_VERSION=$BARE_VERSION-${{ matrix.base-image }}

          # Build container tag
          TAG=ghcr.io/${{ github.repository }}:$PLATFORM_VERSION

          echo "platform-version=$PLATFORM_VERSION" >> $GITHUB_OUTPUT
          echo "container-tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: containers/${{ matrix.base-image }}.dockerfile
          push: true
          tags: ${{ steps.versions.outputs.container-tag }}
          labels: |
            org.opencontainers.image.title=gleam
            org.opencontainers.image.url=https://gleam.run
            org.opencontainers.image.source=https://github.com/gleam-lang/gleam
            org.opencontainers.image.version=${{ steps.versions.outputs.platform-version }}
            org.opencontainers.image.licenses=Apache-2.0
